### ISSUE TITLE
[Bug]: Pen issues on linux-surface

### ISSUE THREAD

**Issue by apmyplol** [LinwoodDev/Butterfly#748]
### What happened?

I noticed a couple of bugs while trying out this very promising program on my linux device.
I noticed that my surface pen is not working when trying to draw, but erasing and selection etc works fine.
When doing the pointer test in the settings it recognizes my pens tip as Input 1, but does not recognize any pressure (pressure is constantly 0). I believe this might be the reason for why drawing does not work with the pen.
Moreover I noticed that the pointer test doesn't recognize the eraser at the back of the pen (Input number is 1) and that the functional button on the pen is recognized as 4 when hovering over the device and as 5 when touching the device with the pen. This makes it impossible to map them, because in the settings its only possible to map 1 and 2.

Other programs (rnote) recognize the eraser correctly.
Im using a surface device with the linux-surface kernel installed. Maybe this problem only appears on linux-surface devices.

### Version

2.2.0

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Sadly, the first issue looks like a known bug, see #238.
The mapping of button 4 and 5 looks just like a small enhancement which i could add.
(kTertiaryButton is 4, 5 is currently not a constant in flutter but I could translate it as "other button", see pointer test if it is the correct button).

**Comment by apmyplol** [comment]
For me, the pen also works like before (i.e. everything except writing with the pen tool) when enabling pen only input.
The pointer test also says pen correctly, when I use the pen.
The fact that the pen input only doesn't work for the drawing tool feels like its maybe unrelated to the issue you mentioned.

**Comment by CodeDoctorDE** [comment]
Quick question: does the button value ever be 0 when having the pen on it?
Otherwise i would just remap the settings a bit that pen input = 1, first button = 2 and second button = 4

**Comment by CodeDoctorDE** [comment]
fixed in 2.2.1-rc.1,
I use now bit masks instead of == (it's okay if you don't understand this :)), this should improve multi button handling and i'm now priorizing the secondary button over the primary button.

**Comment by apmyplol** [comment]
Thank you very much for the quick fix. It will be implemented in the nightly build soon, right? Ill test it out then.
> Quick question: does the button value ever be 0 when having the pen on it? Otherwise i would just remap the settings a bit that pen input = 1, first button = 2 and second button = 4

No, the input is only 0 when the pen doesnt touch the device.

**Comment by CodeDoctorDE** [comment]
Yes it will be available in the next nightly Version next Monday with many other fixes.

That's good, then you don't need to change any settings and it will work out of the box in the next nightly.

**Comment by Postboote1** [comment]
Hello
I ran into the same problem with the pressure of the pen.
In the test it gets recognized but the pressure is 0.
Laser and other stuff however work.
I am on Version 2.2.1 stable

**Comment by CodeDoctorDE** [comment]
yeah it's already known here #238

**Comment by Postboote1** [comment]
Isn't ther any solution yet?

**Comment by CodeDoctorDE** [comment]
Sadly not. Its an issue by the library Im using to capture the input

**Comment by Postboote1** [comment]
oh okay
thought i could use it instead of Rnote

**Comment by apmyplol** [comment]
Would it be possible to include an option like "disable pen pressure recognition" which would always set the pen pressure to 1, i.e. overriding the detected pressure (which is always 0)?
Is that a possible workaround? I think this would make it possible to still use butterfly, even if the pressure isn't recognized.

**Comment by CodeDoctorDE** [comment]
It should already be possible, then it just "simulate" the pressure. If you have issues, feel free to report it

**Comment by WarreTh** [comment]
> It should already be possible, then it just "simulate" the pressure. If you have issues, feel free to report it

Yeah, i tried version 2.2.3, but the pressure of my stylus isnt simulated to 1, so the pen doesnt draw.
I use kubuntu 24.04.

**Comment by CodeDoctorDE** [comment]
Hmm, is it a specific value? Can you try the pointer test and write me the values?

**Comment by WarreTh** [comment]
## On the desktop app:
![Image](https://github.com/user-attachments/assets/b69c8092-7854-4bd8-b674-8e8f5195d7c1)

But the mouse also show 0 pressure on the desktop app, but it still draws

## On the webapp:
![Image](https://github.com/user-attachments/assets/bd5584a7-885d-4e97-a9dc-84988a26a073)

**Comment by CodeDoctorDE** [comment]
Hmm but it looks good...
The pressure should be between 0 and 1...
Im currently not sure how to test it... i currently dont have a linux stylus laptop.
Can you send me a video how it looks like if you draw something?

**Comment by WarreTh** [comment]
I forgot to say that i use a normal linux hp device, with an xppen tablet connected. I have the official xppen drivers installed.

**Comment by CodeDoctorDE** [comment]
Yeah, it looks like it should work. I use the same values as in the pointer test. If the values there is correct, it should work.

**Comment by WarreTh** [comment]
- Using the select tool works
![Image](https://github.com/user-attachments/assets/8110636d-a77e-463f-929e-0f719e815190)

- Using the draw tool doesnt

What should i try, can i export logs or something ?

**Comment by CodeDoctorDE** [comment]
It would be nice if you could try to record the screen so I can look what happened.
Logs aren't available.
It would also be useful if you could upload the .bfly file so i can see if the data is correct

**Comment by WarreTh** [comment]
When i try to save the bfly file, the application just freezes

Here is when i try to draw:

![Image](https://github.com/user-attachments/assets/db159851-08a2-4c64-820b-8fb16fbe9203)

**Comment by CodeDoctorDE** [comment]
Hmm, can you try visiting ~/Documents/Linwood/Butterfly/Documents and try to find the file there?

**Comment by WarreTh** [comment]
I have no such directory

**Comment by CodeDoctorDE** [comment]
Is there no linwood directory inside your documents folder?

**Comment by WarreTh** [comment]
Nope

**Comment by CodeDoctorDE** [comment]
Hmm, can you try to close the note, and export the file from the home screen?

**Comment by WarreTh** [comment]
The application also freezes when i click the home button after drawing with my pen

**Comment by CodeDoctorDE** [comment]
How did you install Butterfly?
Did it save? Then you could just go to home without drawing

**Comment by WarreTh** [comment]
I installed it using flatpak.
I think it didnt save, because i dont find that file.

**Comment by CodeDoctorDE** [comment]
hmm, now it's really tricky for me to reproduce it...
Can you try installing the app without flatpak and try to run it?

**Comment by WarreTh** [comment]
I installed it using the deb file, and i get the same bug.

Then i tried running the appimage and i got this error: 
```
/home/wath/Applications/linwood_butterfly.appimage

/tmp/.mount_linwooESPJnQ/butterfly: symbol lookup error: /tmp/.mount_linwooESPJnQ/butterfly: undefined symbol: g_once_init_enter_pointer

```

**Comment by CodeDoctorDE** [comment]
I have no more ideas right now, can you also try the portable version (or the alternative portable version?).
It looks like it has something to do with glibc, can you see which version do you use?

it looks like the problem isn't really related to flutter: https://github.com/SeaDve/Kooha/issues/283

**Comment by Lygaen** [comment]
Same thing here ! Working fine in other apps,

```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Converting object to an encodable object failed: NaN
#0      _JsonStringifier.writeObject (dart:convert/json.dart:793)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:874)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:784)
#4      _JsonStringifier.writeList (dart:convert/json.dart:844)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:823)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:784)
#7      _JsonStringifier.writeMap (dart:convert/json.dart:874)
#8      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829)
#9      _JsonStringifier.writeObject (dart:convert/json.dart:784)
#10     _JsonStringifier.writeList (dart:convert/json.dart:841)
#11     _JsonStringifier.writeJsonValue (dart:convert/json.dart:823)
#12     _JsonStringifier.writeObject (dart:convert/json.dart:784)
#13     _JsonStringifier.writeMap (dart:convert/json.dart:874)
#14     _JsonStringifier.writeJsonValue (dart:convert/json.dart:829)
#15     _JsonStringifier.writeObject (dart:convert/json.dart:784)
#16     _JsonStringifier.writeList (dart:convert/json.dart:841)
#17     _JsonStringifier.writeJsonValue (dart:convert/json.dart:823)
#18     _JsonStringifier.writeObject (dart:convert/json.dart:784)
#19     _JsonStringifier.writeMap (dart:convert/json.dart:874)
#20     _JsonStringifier.writeJsonValue (dart:convert/json.dart:829)
#21     _JsonStringifier.writeObject (dart:convert/json.dart:784)
#22     _JsonStringStringifier.printOn (dart:convert/json.dart:982)
#23     _JsonStringStringifier.stringify (dart:convert/json.dart:967)
#24     JsonEncoder.convert (dart:convert/json.dart:345)
#25     JsonCodec.encode (dart:convert/json.dart:231)
#26     jsonEncode (dart:convert/json.dart:114)
#27     _encodePage (package:butterfly/bloc/document_state.dart:62)
#28     compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#29     _RemoteRunner._run (dart:isolate:1098)
#30     _RemoteRunner._remoteExecute (dart:isolate:1092)
#31     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#32     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by WarreTh** [comment]
@CodeDoctorDE Are you anything with these errors ?

**Comment by CodeDoctorDE** [comment]
Is this error still present?

**Comment by Lygaen** [comment]
I switched from my distro a week ago but I still had the issue

**Comment by CodeDoctorDE** [comment]
Looks like it wants to write NaN as pressure. I will try to add a check next release and we could see if this fixes the problem?

**Comment by CodeDoctorDE** [comment]
What does it say in the pointer test inside the input settings?

**Comment by CodeDoctorDE** [comment]
Fixed in 2.3.0-beta.3

**Comment by WarreTh** [comment]
Thanks for the fix, it now works perfectly.

**Comment by CodeDoctorDE** [comment]
Perfect, I got some help from someone who had a laptop to test.
Should be available in the next beta next monday
